service: gourbanapp
# app and org for use with dashboard.serverless.com
app: gourbanapp
org: ben888github

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline

functions:
  gourbanapp:
    handler: handler.gourbanapp
    events:
      - http:
          method: GET
          path: /companies
          cors: true
          integration: LAMBDA

  employees:
    handler: handler.employees
    events:
      - http:
          method: GET
          path: /employees
          cors: true
          integration: LAMBDA

  addCompanies:
    handler: handler.addCompanies
    events:
      - http:
          method: POST
          path: /addCompanies
          cors: true
          integration: LAMBDA

  addEmployees:
    handler: handler.addEmployees
    events:
      - http:
          method: POST
          path: /addEmployees
          cors: true
          integration: LAMBDA

  companiesGetById:
    handler: handler.companiesGetById
    events:
      - http:
          method: GET
          path: /companies/{id}
          cors: true
          integration: LAMBDA
          request:
            parameters:
              paths:
                id: true
