service: gourbanapp
# app and org for use with dashboard.serverless.com
app: gourbanapp
org: ben888github

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline

functions:
  gourbanapp:
    handler: handler.gourbanapp
    events:
      - http:
          method: GET
          path: /companies
          cors: true
          integration: LAMBDA
